services:
  kanboard:
    container_name: kanboard
    image: kanboard/kanboard:latest
    ports:
      - "60000:80"
    volumes:
      - kanboard_data:/var/www/app/data
      - kanboard_plugins:/var/www/app/plugins
      - kanboard_ssl:/etc/nginx/ssl
volumes:
  kanboard_data:
  kanboard_plugins:
  kanboard_ssl:
