services:
  stirling-pdf:
    image: frooodle/s-pdf:latest
    ports:
      - '8145:8080'
    volumes:
      - ./data/trainingData:/usr/share/tessdata #Required for extra OCR languages
      - ./data/extraConfigs:/configs
      - ./data/logs:/logs/
      - ./data/customFiles:/customFiles/
    environment:
      - DOCKER_ENABLE_SECURITY=false
      - INSTALL_BOOK_AND_ADVANCED_HTML_OPS=false
      - LANGS=en_GB
